### ISSUE TITLE
Add 'wait-for-it' to Docker

### ISSUE THREAD

**Issue by tim-corley** [tim-corley/django-nextjs-geo-boilerplate#2]
When spinning-up `docker-compose`, the server attempts to make calls to the db before it is ready. Need to ensure that db is ready and then server container starts.

See:
- https://github.com/ufoscout/docker-compose-wait
- https://www.datanovia.com/en/lessons/docker-compose-wait-for-container-using-wait-tool/

# Steps:
1) add script to image via Dockerfile:
```
...
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
...
```
2) call the script via "command" on server service in docker-compose:
```
    env_file:
      - .env.dev
    command: >
      sh -c "/wait && sh migrations.sh && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
```
3) specify which service & port to wait for using an environment variable (.env.dev):
```
# DOCKER-COMPOSE
WAIT_HOSTS=db:5432
```
